// <auto-generated />
using System;
using DiceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiceAPI.Migrations
{
    [DbContext(typeof(DiceContext))]
    partial class DiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("DiceAPI.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Agility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgilityAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgilityMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ArtAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AthleticsAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallisticSkill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallisticSkillAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BallisticSkillMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BriberyAdv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Career")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CareerLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CareerPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharmAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharmAnimalAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClimbAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumeAlcoholAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoolAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Corruption")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentExp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentWounds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dexterity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DexterityAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DexterityMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DodgeAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriveAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EnduranceAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntertainAdv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eyes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Fate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fellowship")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FellowshipAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FellowshipMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Fortune")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GambleAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GossipAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HaggleAdv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hair")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Initiative")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitiativeAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InitiativeMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Intelligence")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntelligenceAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntelligenceMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntimidateAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntuitionAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeadershipAdv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LongTermAmbition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MeleeAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeleeBasicAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Movement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NavigationAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutdoorSurvivalAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerceptionAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resilience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resolve")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RideAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RowAdv")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortTermAmbition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpentExp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusTier")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StealthAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Strength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrengthAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrengthMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Toughness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToughnessAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToughnessMod")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponSkill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponSkillAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeaponSkillMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Willpower")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WillpowerAdv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WillpowerMod")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wounds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("DiceAPI.Models.CharacterSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Advances")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Characteristic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSpecialisation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("DiceAPI.Models.DiceRoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sides")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DiceRolls");
                });

            modelBuilder.Entity("DiceAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DiceAPI.Models.Character", b =>
                {
                    b.HasOne("DiceAPI.Models.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DiceAPI.Models.CharacterSkill", b =>
                {
                    b.HasOne("DiceAPI.Models.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("DiceAPI.Models.Character", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("DiceAPI.Models.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
